name = "WebAssemblyInterfaces"
uuid = "74d8c2bb-7b3a-4d47-ac1c-f80c5e9b8189"
authors = ["Tom Short"]
version = "1.1.0"

[weakdeps]
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"

[compat]
StaticTools = "v0.8"
julia = "1.9"

[extensions]
WebAssemblyInterfacesStaticToolsExt = "StaticTools"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"

[targets]
test = ["Test", "StaticTools"]
